name: "Check for newer image versions"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * MON *"

jobs:
  digest-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: navikt/digestabot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: navno