---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: navno
  labels:
    team: navno
spec:
  image: {{image}}
  port: 3001
  liveness:
    path: /sok/api/internal/isAlive
    initialDelay: 5
  readiness:
    path: /sok/api/internal/isReady
    initialDelay: 5
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  replicas:
  {{#with replicas}}
    min: {{min}}
    max: {{max}}
  {{/with}}
  accessPolicy:
    outbound:
      rules:
        - application: {{dekoratorenAppName}}
          namespace: personbruker
        - application: navno-search-api
          namespace: navno
      external:
        - host: {{appHost}}
        - host: {{searchHost}}
  resources:
  {{#with resources}}
    limits:
      cpu: {{limits.cpu}}
      memory: {{limits.memory}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
  {{/with}}
