---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 3001
  liveness:
    path: /sok/api/internal/isAlive
    initialDelay: 5
  readiness:
    path: /sok/api/internal/isReady
    initialDelay: 5
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  replicas:
  {{#with replicas}}
    min: {{min}}
    max: {{max}}
  {{/with}}
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
      external:
        - host: {{xpHost}}
  resources:
  {{#with resources}}
    limits:
      cpu: {{limits.cpu}}
      memory: {{limits.memory}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
  {{/with}}
