name: Build docker image
on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      deployEnv:
        required: true
        type: string
      imagename:
        required: true
        type: string
      APP_ORIGIN:
        required: true
        type: string
      SEARCH_URL:
        required: true
        type: string
    secrets:
      READER_TOKEN:
        required: true
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true

jobs:
  build-and-deploy:
    name: Build docker image and deploy to nais k8s
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployEnv }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
      - name: Set app environmment
        run: |
          cat > .env <<EOF
          NODE_ENV=production
          APP_BASE_PATH=/sok
          APP_ORIGIN=${{ inputs.APP_ORIGIN }}
          SEARCH_URL=${{ inputs.SEARCH_URL }}
          ENV=${{ inputs.deployEnv }}
          EOF
      - name: Nextjs cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build application
        run: npm run build
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: personbruker
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          image_suffix: ${{ inputs.imagename }}
      - uses: nais/deploy/actions/deploy@main
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: .nais/config.yml
          VAR: image=${{ steps.docker-push.outputs.image }}
          VARS: .nais/vars-${{ inputs.deployEnv }}.yml