name: Deploy to dev1
on:
  workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      cluster: dev-gcp
      deployEnv: dev1
      imagename: dev1-deploy
      APP_ORIGIN: https://www.ekstern.dev.nav.no
      SEARCH_URL: https://navno-search-api.intern.dev.nav.no/content/compatible-search
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}