name: Deploy to prod
on:
  release:
    types: [released]

jobs:
  deploy:
    if: github.event.release.target_commitish == 'master'
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      packages: "write"
    with:
      cluster: prod-gcp
      deployEnv: prod
      imagename: release-${{ github.ref_name }}
      APP_ORIGIN: https://www.nav.no
      XP_ORIGIN: https://www.nav.no
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
