name: Deploy to dev
on:
  workflow_dispatch

jobs:
  deploy-dev:
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      cluster: dev-gcp
      deployEnv: dev
      imagename: dev-deploy
      APP_ORIGIN: https://www.ansatt.dev.nav.no
      SEARCH_URL: https://navno-search-api.ekstern.dev.nav.no/content/search
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}