name: Deploy-to-prod
on:
  release:
    types: [released]

jobs:
  deploy:
    if: github.event.release.target_commitish == 'master'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      cluster: prod-gcp
      imagename: release-${{ github.ref_name }}
      varsFile: vars-prod.yml
      APP_ORIGIN: https://www.nav.no
      DECORATOR_URL: https://www.nav.no/dekoratoren
      XP_ORIGIN: https://www.nav.no
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
