name: Deploy to prod on dispatch
on:
  workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      cluster: prod-gcp
      deployEnv: prodbeta
      imagename: release-${{ github.ref_name }}
      APP_ORIGIN: https://www.nav.no
      XP_ORIGIN: https://www.nav.no
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
