name: Deploy to dev2
on:
  workflow_dispatch

jobs:
  deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      cluster: dev-gcp
      deployEnv: dev2
      imagename: dev2-deploy
      APP_ORIGIN: https://www-2.ekstern.dev.nav.no
      SEARCH_URL: https://portal-admin-q6.oera.no
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}